[package]
name = "payloads"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
libaes = "0.7.0"
winapi = { version = "0.3.9", features = ["memoryapi", "processthreadsapi", "winbase", "winnt"] }
