[package]
name = "Fibre-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
litcrypt2 = "0.1.3"
windows-sys = { version = "0.59.0", features = ["Win32_System_Threading", "Win32_System_Memory", "Win32_Foundation"] }
